### ISSUE TITLE
Going live?

### ISSUE THREAD

**Issue by kartben** [msangoi/leshan-website#4]
Hi Manu,

Do you need help pushing the website live?
The only thing you need to do, I believe, is to push to http://git.eclipse.org/c/www.eclipse.org/leshan.git/ :)

Also, let me know if you need help with #3 

ping @jvermillard @sbernard31

**Comment by msangoi** [comment]
Hi Benjamin, 

Sorry for the delay, I wanted to polish a bit the website before going live (logo integration, content alignment...).
But if you're ok with this first version, I will push it to the eclipse repo. And add the Google analytics tracker.

**Comment by sbernard31** [comment]
Do we really need Google Analytics for this kind of site? 
If we really need Web Analytics Software, I prefer to ask to eclipse foundation if it's possible to have a [Piwik](https://piwik.org/) instance.

**Comment by jvermillard** [comment]
@sbernard31 let's open a bugzilla @ eclipse.org with why GA is not so nice and propose piwik?

**Comment by sbernard31** [comment]
I can do that but personally I don't need stats on Leshan web site.
So I would like to be sure that we really need that ...
We already have github stats (and maybe [maven stats](http://blog.sonatype.com/2010/12/now-available-central-download-statistics-for-oss-projects/)) that's not enough ? 

(There is also an eclipse download stats infrastructure which could be used (https://wiki.eclipse.org/Equinox_p2_download_stats), even if it should be used for download stats rather than visit stats)

An article about "[why we should use Piwik?](http://www.statstory.com/some-reasons-to-choose-piwik-analytics-over-google-analytics/)" (For me privacy concern is the more important part)

**Comment by kartben** [comment]
@sbernard31
The main reason we kindly ask our projects to install a GA tracker is to be able to produce a consolidated set of metrics for our Eclipse IoT projects. You can see [previous reports](https://wiki.eclipse.org/IoT/Community_metrics#2015) on our Wiki, with the latest metrics for August [here](https://docs.google.com/presentation/d/1mGcFY1f1cJly5LhRzya3O5GT4W0cvVrUZNNpUq-wkb8/edit).
It's actually _very_ helpful to recruit interested parties and contributors, and to be able to demonstrate that projects are getting traction. All in all, it really helps building the reputation of the projects and technologies.

At the moment I prefer Google Analytics since it has nice APIs to easily allow to consolidate the metrics across all the projects, but maybe Piwik can provide something similar.

**Comment by sbernard31** [comment]
Ok. It's hard for me to imagine that people choose a technology because there is a lot of visitors on its website. But let's suppose that's true.
So I will open a bug to ask for a Piwik instance.

**Comment by sbernard31** [comment]
The bug is opened :)
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476966

**Comment by msangoi** [comment]
Done!
